import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
    const content = await fetch(
        'https://nextbugtest.free.beeceptor.com/about'
    ).then(response => {
        return response.json();
    });

    return {
        props: { ...content },
    };
}

export default function About(props) {
    const { header, footer } = props;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>{header.name}</h1>
            <nav>
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
            </nav>
            <h5>{footer.name}</h5>
        </div>
    );
}
